import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "./components/appHeader";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader>
          <AntdRegistry>{children}</AntdRegistry>
        </AppHeader>
      </body>
    </html>
  );
}
